language: java
jdk: openjdk7
cache: apt

branches:
  only: master
deploy:
  provider: heroku
  api_key:
    secure: FZqgwp7zWinvxxQquiFhQOoLEcSiePgE1JIH5Ub7eaYF45SECUwJakfzzhmIVgvUnNwP/OcD6/F3tTpBbkPlwQk7WHPsFKPXBiSnUga+5jOQHdF5gCKlfFfHLjVlcCy5rDHFtxReHXoSAKIJgyRLWy0LnWDCddSAoN/iXijiMVQ=
  app: tictackesha
  on:
    repo: sidannaverkefnihopur1/TicTacKesha
after_script:
  - "export STAGING_SERVER=http://tictackesha.herokuapp.com/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "sh bin/selenium_test_xvfb"
after_success:
  - mvn test jacoco:report coveralls:jacoco
notifications:
  email:
    recipients:
      - axelb10@ru.is
    on_success: change
    on_failure: always