language: java
jdk: openjdk7

after_script:
  - "export STAGING_SERVER=http://tictackesha.herokuapp.com"
  - "export DISPLAY=:99.9"
  - "sh bin/selenium_test_xvfb"

deploy:
  provider: heroku
  api_key:
    secure: FZqgwp7zWinvxxQquiFhQOoLEcSiePgE1JIH5Ub7eaYF45SECUwJakfzzhmIVgvUnNwP/OcD6/F3tTpBbkPlwQk7WHPsFKPXBiSnUga+5jOQHdF5gCKlfFfHLjVlcCy5rDHFtxReHXoSAKIJgyRLWy0LnWDCddSAoN/iXijiMVQ=
  app: tictackesha
  on:
    repo: sidannaverkefnihopur1/TicTacKesha
