language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: FZqgwp7zWinvxxQquiFhQOoLEcSiePgE1JIH5Ub7eaYF45SECUwJakfzzhmIVgvUnNwP/OcD6/F3tTpBbkPlwQk7WHPsFKPXBiSnUga+5jOQHdF5gCKlfFfHLjVlcCy5rDHFtxReHXoSAKIJgyRLWy0LnWDCddSAoN/iXijiMVQ=
  app: tictackesha
  on:
    repo: sidannaverkefnihopur1/TicTacKesha
